ccflags-y += -I $(srctree)/techpack/camera-legacy-m
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/sensor/io
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
