ccflags-y += -Itechpack/camera-legacy
ccflags-y += -Itechpack/camera-legacy/common
ccflags-y += -Itechpack/camera-legacy/sensor/io
ccflags-y += -Itechpack/camera-legacy/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
