ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_ir_cut.o
