obj-$(CONFIG_MACH_XIAOMI_UGG) += ugg_fpsensor.o
obj-$(CONFIG_FINGERPRINT_FPC1020_UGG) += fpc_ugg/
obj-$(CONFIG_FINGERPRINT_GF3208_UGG) += gf3208_ugg/

obj-$(CONFIG_FINGERPRINT_FPC1020) += fpc_santoni/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208) += goodix_santoni/
