ccflags-y += -Idrivers/media/video/msm
ccflags-y += -I $(srctree)/techpack/camera-legacy/common
ccflags-y += -I $(srctree)/techpack/camera-legacy
ccflags-y += -I $(srctree)/techpack/camera-legacy/pproc/cpp
ccflags-y += -I $(srctree)/techpack/camera-legacy/msm_buf_mgr/

obj-$(CONFIG_MSM_FD) += msm_fd_dev.o msm_fd_hw.o
