ccflags-y += -Idrivers/media/platform/msm/camera_v2-land
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
