ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
