ccflags-y += -Idrivers/media/platform/msm/camera_v2-land
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
