ccflags-y += -Itechpack/camera-legacy-m
ccflags-y += -Itechpack/camera-legacy-m/common
ccflags-y += -Itechpack/camera-legacy-m/msm_vb2
ccflags-y += -Itechpack/camera-legacy-m/camera
ccflags-y += -Itechpack/camera-legacy-m/sensor/io
ccflags-y += -Itechpack/camera-legacy-m/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
