ccflags-y += -Itechpack/camera-legacy
ccflags-y += -Itechpack/camera-legacy/common
ccflags-y += -Itechpack/camera-legacy/sensor/io
ccflags-y += -Itechpack/camera-legacy/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MACH_FAMILY_XIAOMI_ULYSSE) += msm_eeprom_xiaomi_ulysse.o
