ccflags-y += -Itechpack/camera-legacy-m
ccflags-y += -Itechpack/camera-legacy-m/common
ccflags-y += -Itechpack/camera-legacy-m/sensor/io
ccflags-y += -Itechpack/camera-legacy-m/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
