ccflags-y += -Itechpack/camera-legacy-m/
ccflags-y += -Itechpack/camera-legacy-m/common
ccflags-y += -Itechpack/camera-legacy-m/sensor
ccflags-y += -Itechpack/camera-legacy-m/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
