ccflags-y += -I $(srctree)/techpack/camera-legacy
ccflags-y += -I $(srctree)/techpack/camera-legacy/common
ccflags-y += -I $(srctree)/techpack/camera-legacy/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_csid.o
