obj-$(CONFIG_MSM_USB_POWER_SUPPLY_MI8937) += msm_usb_psy.o

obj-$(CONFIG_CHARGER_BQ2560X) += bq2560x/
obj-$(CONFIG_FUEL_GAUGE_BQ27426) += bq27426/
obj-$(CONFIG_BATTERY_CW2015) += cw2015_rolex/
obj-$(CONFIG_GAUGE_CW2017) += cw2017_tiare/
obj-y += qcom/
obj-$(CONFIG_SMB358_CHARGER) += smb358_rolex/
