ccflags-y += -Idrivers/media/video/msm
ccflags-y += -Itechpack/camera-legacy-m/common
ccflags-y += -Itechpack/camera-legacy-m
ccflags-y += -Itechpack/camera-legacy-m/pproc/cpp
ccflags-y += -Itechpack/camera-legacy-m/msm_buf_mgr/

obj-$(CONFIG_MSM_FD) += msm_fd_dev.o msm_fd_hw.o
