ccflags-y += -I $(srctree)/techpack/camera-legacy
ccflags-y += -I $(srctree)/techpack/camera-legacy/isp/
ccflags-y += -I $(srctree)/techpack/camera-legacy/sensor/io
ccflags-y += -I $(srctree)/techpack/camera-legacy/common
ccflags-y += -I $(srctree)/techpack/camera-legacy/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
