ccflags-y += -Itechpack/camera-legacy-m/sensor/cci
ccflags-y += -Itechpack/camera-legacy-m
ccflags-y += -Itechpack/camera-legacy-m/common
ccflags-y += -Itechpack/camera-legacy-m/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
