ccflags-y += -I $(srctree)/techpack/camera-legacy-m/sensor/cci
ccflags-y += -I $(srctree)/techpack/camera-legacy-m
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
