ccflags-y += -I $(srctree)/techpack/camera-legacy-m
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
