ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o

obj-$(CONFIG_MACH_XIAOMI_ROVA) += msm_eeprom_insensor_ov13850.o
obj-$(CONFIG_MACH_XIAOMI_TIARE) += msm_eeprom_insensor_hi556.o
