ccflags-y += -I $(srctree)/techpack/camera-legacy-m
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
