ccflags-y += -Idrivers/media/platform/msm/camera_v2-land
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
