ccflags-y += -Idrivers/media/platform/msm/camera_v2-land
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
