ccflags-y += -I $(srctree)/techpack/camera-legacy/jpeg_10
ccflags-y += -I $(srctree)/techpack/camera-legacy/sensor/io
ccflags-y += -I $(srctree)/techpack/camera-legacy/common

obj-$(CONFIG_MSMB_JPEG) += msm_jpeg_dev.o msm_jpeg_sync.o msm_jpeg_core.o msm_jpeg_hw.o msm_jpeg_platform.o
