ccflags-y += -I $(srctree)/techpack/camera-legacy-m
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/isp/
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/sensor/io
ccflags-y += -I $(srctree)/techpack/camera-legacy-m/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
