#include "msmb_camera.h"

#define MSM_CAMERA_SUBDEV_EXT          (MSM_CAMERA_SUBDEV_BASE + 17)

#undef MSM_CAMERA_SUBDEV_IR_LED
#undef MSM_CAMERA_SUBDEV_IR_CUT
#undef MSM_CAMERA_SUBDEV_EXT
#undef MSM_CAMERA_SUBDEV_TOF
#undef MSM_CAMERA_SUBDEV_LASER_LED
