ccflags-y += -I $(srctree)/techpack/camera-legacy
ccflags-y += -I $(srctree)/techpack/camera-legacy/common
ccflags-y += -I $(srctree)/techpack/camera-legacy/sensor/io
ccflags-y += -I $(srctree)/techpack/camera-legacy/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
