ccflags-y += -Itechpack/camera-legacy-m
ccflags-y += -Itechpack/camera-legacy-m/common
ccflags-y += -Itechpack/camera-legacy-m/sensor/io
ccflags-y += -Itechpack/camera-legacy-m/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
