ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
