ccflags-y += -Idrivers/media/platform/msm/camera_v2-land
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
