ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-santoni/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ ir_led/ ir_cut/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
