#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
ccflags-y := $(call cc-disable-warning, fortify-source)
ccflags-y += $(call cc-disable-warning, invalid-source-encoding)
obj-$(CONFIG_TOUCHSCREEN_FT5446_MI439) += focaltech_test_ft5446dqs_q02.o
