obj-y += fp_init.o

obj-$(CONFIG_FINGERPRINT_FPC1020_UGG) += fpc_ugg/
obj-$(CONFIG_FINGERPRINT_GF3208_UGG) += gf3208_ugg/

obj-$(CONFIG_FINGERPRINT_FPC1020_SANTONI) += fpc_santoni/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208_SANTONI) += goodix_santoni/
